// @ts-check
const { test, expect } = require('@playwright/test');

/**
 * Seed recovery from an image's prompt block on drag-in (#58, v0.12.4).
 *
 * Loads an existing output image through the real drag-in entry
 * (app.handleFile, which drag-drop and File > Open both use) and checks the
 * SmartResCalc node comes back with the seed that MADE the image (from the
 * prompt block), not the one-run-stale workflow property that images made
 * with v0.12.2 carry.
 *
 * Fixture: ComfyUI/output/seed_probe/probe_00001_.png, generated by
 * tests/e2e/seed-metadata.spec.js BEFORE the 0.12.3 metadata fix, so its
 * workflow property is the sentinel 111111111111111 while its prompt block
 * holds the real seed 91987083756186. If the fixture is missing, run
 * seed-metadata.spec.js once on a pre-0.12.3 checkout, or any image whose
 * tests/one-offs/measure_seed_metadata.py row shows own=False.
 *
 * Requires ComfyUI running at localhost:8188. Queues nothing.
 */

const FIXTURE = { filename: 'probe_00001_.png', subfolder: 'seed_probe', type: 'output' };
const FIXTURE_URL = `/view?filename=${encodeURIComponent(FIXTURE.filename)}&subfolder=${encodeURIComponent(FIXTURE.subfolder)}&type=${FIXTURE.type}`;

// --- PNG tEXt rewriting (Node side), to derive a second fixture from the first ---
const CRC_TABLE = (() => {
    const t = new Uint32Array(256);
    for (let n = 0; n < 256; n++) {
        let c = n;
        for (let k = 0; k < 8; k++) c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
        t[n] = c >>> 0;
    }
    return t;
})();
function crc32(buf) {
    let c = 0xFFFFFFFF;
    for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xFF] ^ (c >>> 8);
    return (c ^ 0xFFFFFFFF) >>> 0;
}
/** Return a copy of a PNG with the tEXt chunk `key` replaced by transform(oldText). */
function rewritePngText(buf, key, transform) {
    const parts = [buf.subarray(0, 8)];
    let off = 8;
    while (off + 8 <= buf.length) {
        const size = buf.readUInt32BE(off);
        const tag = buf.toString('latin1', off + 4, off + 8);
        const chunk = buf.subarray(off, off + 12 + size);
        if (tag === 'tEXt') {
            const body = buf.subarray(off + 8, off + 8 + size);
            const nul = body.indexOf(0);
            if (body.toString('latin1', 0, nul) === key) {
                const newText = Buffer.from(transform(body.toString('utf8', nul + 1)), 'utf8');
                const newBody = Buffer.concat([body.subarray(0, nul + 1), newText]);
                const typeAndData = Buffer.concat([Buffer.from('tEXt', 'latin1'), newBody]);
                const len = Buffer.alloc(4); len.writeUInt32BE(newBody.length);
                const crc = Buffer.alloc(4); crc.writeUInt32BE(crc32(typeAndData));
                parts.push(len, typeAndData, crc);
                off += 12 + size;
                continue;
            }
        }
        parts.push(chunk);
        off += 12 + size;
    }
    return Buffer.concat(parts);
}
const FIXTURE_PROMPT_SEED = 91987083756186;    // what Python received for this image
const FIXTURE_STALE_PROP = 111111111111111;    // what its workflow block carries
const JSON_SEED = 582123831103465;

test.setTimeout(120000);

async function bootPage(page, consoleLines) {
    page.on('console', msg => consoleLines.push(msg.text()));
    await page.goto('/');
    await page.evaluate(() => { localStorage.setItem('DEBUG_SMART_RES_CALC', 'true'); });
    await page.reload();
    await page.waitForFunction(() => !!(window.app && window.app.graph && window.LiteGraph), null, { timeout: 60000 });
    await page.waitForTimeout(1500);
}

/** Read the first SmartResolutionCalc node's seed state after a load (polls up to 8 s for it to appear). */
async function readSeedState(page) {
    return page.evaluate(async () => {
        const t0 = Date.now();
        let node = null;
        while (Date.now() - t0 < 8000) {
            node = (window.app.graph._nodes || []).find(n => n.comfyClass === 'SmartResolutionCalc');
            if (node) break;
            await new Promise(r => setTimeout(r, 200));
        }
        if (!node) return { error: 'SmartResolutionCalc node not found within 8s' };
        // Give the configure hook a moment past node appearance.
        await new Promise(r => setTimeout(r, 300));
        const sw = node.widgets?.find(w => w.name === 'fill_seed');
        return {
            id: node.id, prop: node.properties?.dazzle_last_seed ?? null,
            lastSeed: sw?.lastSeed ?? null, value: JSON.parse(JSON.stringify(sw?.value ?? null)),
            randomizeMode: sw?.randomizeMode, display: sw?.getDisplayState?.().text ?? null,
        };
    });
}

test('drag-in of a pre-0.12.3 image recovers the seed from its prompt block', async ({ page }) => {
    const consoleLines = [];
    await bootPage(page, consoleLines);

    const loaded = await page.evaluate(async ({ f }) => {
        const url = `/view?filename=${encodeURIComponent(f.filename)}&subfolder=${encodeURIComponent(f.subfolder)}&type=${f.type}`;
        const res = await fetch(url);
        if (!res.ok) return { error: `fixture fetch ${res.status}` };
        const blob = await res.blob();
        const file = new File([blob], f.filename, { type: 'image/png' });
        window.app.graph.clear();
        const hookIsOurs = String(window.app.handleFile).includes('pendingImageSeeds');
        let sameApp = null;
        try { sameApp = (await import('/scripts/app.js')).app === window.app; } catch (e) { sameApp = 'import failed: ' + e; }
        await window.app.handleFile(file);
        return { ok: true, size: blob.size, hookIsOurs, sameApp };
    }, { f: FIXTURE });
    console.log('load diagnostics:', JSON.stringify(loaded));
    expect(loaded.hookIsOurs, 'our hook must be the outermost app.handleFile wrapper').toBe(true);
    expect(loaded.error, JSON.stringify(loaded)).toBeUndefined();

    const s = await readSeedState(page);
    console.log('after drag-in:', JSON.stringify(s));
    console.log('--- relevant console lines ---');
    for (const l of consoleLines.filter(l => /Image Seeds|Installed|\[configure\]|handleFile|SmartResCalc\].*(Error|error)|TypeError|ReferenceError/.test(l)).slice(0, 40)) console.log(l);
    expect(s.error).toBeUndefined();
    expect(s.lastSeed).toBe(FIXTURE_PROMPT_SEED);          // the image's own seed ...
    expect(s.lastSeed).not.toBe(FIXTURE_STALE_PROP);       // ... not the stale workflow property
    expect(s.prop).toBe(FIXTURE_PROMPT_SEED);              // mirrored so a later save carries it
    expect(s.value).toEqual({ on: true, value: -1 });      // widget mode untouched (random)
    expect(s.randomizeMode).toBe(true);
    expect(s.display).toBe(String(FIXTURE_PROMPT_SEED));   // readout shows it
    const line = consoleLines.find(l => /\[configure\] Node \S+: seed from image prompt 111111111111111 -> 91987083756186/.test(l));
    expect(line, 'expected a "seed from image prompt" console line').toBeTruthy();
});

test('a stale pending entry does not leak into the next image (mutation W7)', async ({ page }) => {
    const consoleLines = [];
    await bootPage(page, consoleLines);

    // Second fixture, derived from the first: same workflow block (stale
    // property 111111111111111), but the prompt block's SmartResCalc entry is
    // renamed so it carries no usable seed. Correct behaviour: the second
    // drag-in hydrates from the property only.
    const original = Buffer.from(await (await page.request.get(FIXTURE_URL)).body());
    const noSeed = rewritePngText(original, 'prompt', text => {
        const p = JSON.parse(text);
        for (const entry of Object.values(p)) if (entry.class_type === 'SmartResolutionCalc') entry.class_type = 'SmartResolutionCalc__disabled';
        return JSON.stringify(p);
    });
    expect(noSeed.length).toBeGreaterThan(0);

    const r = await page.evaluate(async ({ url, noSeedB64 }) => {
        const app = window.app;
        const readState = async () => {
            const t0 = Date.now();
            let node = null;
            while (Date.now() - t0 < 8000) {
                node = (app.graph._nodes || []).find(n => n.comfyClass === 'SmartResolutionCalc');
                if (node) break;
                await new Promise(r => setTimeout(r, 200));
            }
            await new Promise(r => setTimeout(r, 300));
            const sw = node?.widgets?.find(w => w.name === 'fill_seed');
            return node ? { lastSeed: sw?.lastSeed ?? null, prop: node.properties?.dazzle_last_seed ?? null } : { error: 'node missing' };
        };
        const blob = await (await fetch(url)).blob();
        app.graph.clear();
        await app.handleFile(new File([blob], 'seeded.png', { type: 'image/png' }));
        const first = await readState();
        const bytes = Uint8Array.from(atob(noSeedB64), c => c.charCodeAt(0));
        app.graph.clear();
        await app.handleFile(new File([bytes], 'no-seed.png', { type: 'image/png' }));   // within the TTL of the first
        const second = await readState();
        return { first, second };
    }, { url: FIXTURE_URL, noSeedB64: noSeed.toString('base64') });
    console.log('stale-entry check:', JSON.stringify(r));
    expect(r.first.lastSeed).toBe(FIXTURE_PROMPT_SEED);
    expect(r.second.lastSeed).toBe(FIXTURE_STALE_PROP);       // property hydration only
    expect(r.second.prop).toBe(FIXTURE_STALE_PROP);
    expect(consoleLines.filter(l => l.includes('seed from image prompt')).length).toBe(1);   // only the first load
});

test('handleFile arguments and receiver are forwarded to the wrapped handler (mutation W9)', async ({ page }) => {
    await bootPage(page, []);
    const r = await page.evaluate(async () => {
        const app = window.app;
        window.__spy = null;
        // Plant a spy as the current handler; the extension's re-check timer
        // (250 ms .. 8 s after setup) wraps whatever is current, so wait for it.
        app.handleFile = async function spyHandleFile(file, source, opts) {
            window.__spy = { name: file?.name, source, opts, thisIsApp: this === window.app };
        };
        const t0 = Date.now();
        while (!String(app.handleFile).includes('pendingImageSeeds') && Date.now() - t0 < 12000) {
            await new Promise(r => setTimeout(r, 200));
        }
        const wrapped = String(app.handleFile).includes('pendingImageSeeds');
        const file = new File([new Uint8Array([1, 2, 3])], 'not-an-image.txt', { type: 'text/plain' });
        await app.handleFile(file, 'file_button', { deferWarnings: true });
        return { wrapped, waitedMs: Date.now() - t0, spy: window.__spy };
    });
    console.log('forwarding check:', JSON.stringify(r));
    expect(r.wrapped).toBe(true);
    expect(r.spy).toEqual({ name: 'not-an-image.txt', source: 'file_button', opts: { deferWarnings: true }, thisIsApp: true });
});

test('a JSON reload (no image) is unchanged: property hydration only, no prompt-seed line', async ({ page }) => {
    const consoleLines = [];
    await bootPage(page, consoleLines);

    await page.evaluate(async ({ seed }) => {
        const app = window.app;
        app.graph.clear();
        const node = LiteGraph.createNode('SmartResolutionCalc');
        node.pos = [100, 100];
        app.graph.add(node);
        const sw = node.widgets.find(w => w.name === 'fill_seed');
        sw.value = { on: true, value: -1 };
        if (sw.setRandomMode) sw.setRandomMode(true);
        node.properties.dazzle_last_seed = seed;
        sw.lastSeed = null;
        const wf = app.graph.serialize();
        await app.loadGraphData(wf);
    }, { seed: JSON_SEED });
    await page.waitForTimeout(2000);

    const s = await readSeedState(page);
    console.log('after JSON reload:', JSON.stringify(s));
    expect(s.error).toBeUndefined();
    expect(s.lastSeed).toBe(JSON_SEED);
    expect(s.prop).toBe(JSON_SEED);
    expect(s.display).toBe(String(JSON_SEED));
    expect(consoleLines.some(l => l.includes('seed from image prompt'))).toBe(false);
    expect(consoleLines.some(l => /\[configure\] Node \S+: hydrated lastSeed=582123831103465/.test(l))).toBe(true);
});
